# Generated by Django 5.1.7 on 2025-03-18 21:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('address', models.CharField(blank=True, default='Jamcity', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('machine_type', models.CharField(choices=[('Milk', 'Milk'), ('Juice', 'Juice'), ('Cooking oil', 'Cooking oil'), ('Other', 'Other')], default='Milk', max_length=255)),
                ('total_volume', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('initial_tokens', models.PositiveIntegerField(default=15)),
                ('remaining_tokens', models.PositiveIntegerField(default=15)),
                ('days_used', models.PositiveIntegerField(default=0)),
                ('cost_per_day', models.FloatField(default=3.0)),
                ('tokens_per_month', models.PositiveIntegerField(default=30)),
                ('last_processed_date', models.DateField(default=datetime.datetime.now)),
                ('activated', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vending_machine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_made', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('token_pack', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='base.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('customers_served', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(default='Kitengela', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_shop', to='base.shop'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('volume', models.FloatField(default=0.0)),
                ('token_used', models.FloatField(default=1)),
                ('total_amount', models.FloatField(default=0.0)),
                ('total_volume', models.FloatField(default=0.0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='base.machine')),
            ],
        ),
    ]
