# Generated by Django 5.1.7 on 2025-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_relaycontroller_relayoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
