# Generated by Django 5.1.7 on 2025-03-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_machine_location_remove_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
