# Generated by Django 5.1.7 on 2025-03-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_machine_location_machine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='location',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
    ]
