# Generated by Django 5.1.7 on 2025-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_machine_location_remove_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
