# Generated by Django 5.1.7 on 2025-03-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_client_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_shop', to='base.shop'),
        ),
    ]
