# Generated by Django 5.1.7 on 2025-03-29 20:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_machine_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique identifier for the device (e.g., 0677FF565165854967054030)",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name for the device",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relay_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RelayChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("IN", "Input"), ("OUT", "Output")], max_length=3
                    ),
                ),
                (
                    "channel_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32),
                        ]
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ON", "On"), ("OFF", "Off")],
                        default="OFF",
                        max_length=3,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of what this channel controls",
                        max_length=100,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="base.relaydevice",
                    ),
                ),
            ],
            options={
                "ordering": ["device", "channel_type", "channel_number"],
                "unique_together": {("device", "channel_type", "channel_number")},
            },
        ),
    ]
